import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";


// Google fonts
const mont = Montserrat({ subsets: ["latin"], weight: ["600", "700", "800"], variable: "--font-mont" });
const inter = Inter({ subsets: ["latin"], weight: ["300", "400", "600", "700"], variable: "--font-inter" });

// Enhanced metadata with more comprehensive information
export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "TypeScript"],
  authors: [{ name: "Next.js Team" }],
  creator: "Next.js Team",
  publisher: "Vercel",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

// Type-safe props interface for better maintainability
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ }: RootLayoutProps) {
  // Error boundary could be added here for better error handling
  return (
    <html lang="en" suppressHydrationWarning={false}>
      <body
        className={`${mont.variable} ${inter.variable} antialiased bg-white dark:bg-black text-black dark:text-white`}
        suppressHydrationWarning={false}
      >
      </body>
    </html>
  );
}
